Add no_std support
LPGhatguy/nonmax pull request #8
Opened 2020-10-17 08:12 UTC by MaulingMonkey

2020-10-17 22:02 UTC, LPGhatguy requested changes
Happy to see the GitHub Actions workflow update alongside this change, nice! I'm also pleased to see that this PR is mechanical and straightforward.

Can you add a note to `lib.rs` about disabling the `std` feature to get support for `no_std`? I always find it frustrating when a crate's feature list is not documented.

I would like to keep the doc examples using `std` if we can. Does `#![no_std]`  apply to doc examples, or are they compiled separately? Can we use a trick like a hidden `extern crate core as std` line if so?

2020-10-18 17:36 UTC, MaulingMonkey commented
> Happy to see the GitHub Actions workflow update alongside this change, nice! I'm also pleased to see that this PR is mechanical and straightforward.

Gotta have that CI coverage ;)

> Can you add a note to `lib.rs` about disabling the `std` feature to get support for `no_std`? I always find it frustrating when a crate's feature list is not documented.

I waffled back and forth a bit on formatting, but: https://github.com/LPGhatguy/nonmax/pull/8/commits/6a169d5c118dbf1584904d4bcbe6d6a545762917

> I would like to keep the doc examples using `std` if we can. Does `#![no_std]` apply to doc examples, or are they compiled separately? Can we use a trick like a hidden `extern crate core as std` line if so?

It looks like we can use std without tricks in doc comments, to my suprise: https://github.com/LPGhatguy/nonmax/pull/8/commits/58e85c7a49601235be5d010ffb4e8a58e666fcbb

2020-10-18 18:19 UTC, LPGhatguy approved these changes

2020-10-18 18:19 UTC, merged

2020-10-18 18:19 UTC, LPGhatguy commented
Thanks a bunch! I might actually use this crate in a `no_std` project I'm working on now...